// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Lab1.Models;

public partial class Course
{
    [Key]
    public int id { get; set; }

    [Column("Crs_name")]
    [StringLength(50)]
    public string Crs_name { get; set; }

    [Column("Crs_desc")]
    [StringLength(100)]
    public string Crs_desc { get; set; }

    public int? Duration { get; set; }
}